### ISSUE TITLE
CEN config version in config in github doesn't match what is in DNAnexus

### ISSUE THREAD

**Issue by Addy81** [eastgenomics/egg5_dias_CEN_config#53]
File as described in testing file-Gf6fQg046k53kjXKPyX17xv0 doesn't match the file released in this repo. The version field in DNAnexus hasn't been changed and still states 3.0.1.

Job logs from testing:
<img width="947" alt="image" src="https://github.com/eastgenomics/egg5_dias_CEN_config/assets/33088252/209cbb79-be49-403f-bddb-ed0c49e633df">

File in github:
<img width="969" alt="image" src="https://github.com/eastgenomics/egg5_dias_CEN_config/assets/33088252/671b1b25-e73c-47af-be52-92baf04db0f7">

Diff of latest two versions in DNAnexus: 

diff -sy --suppress-common-lines <(dx cat file-Gf6fQg046k53kjXKPyX17xv0) <(dx cat file-Gf1PzX04K7XfQbq0Vqqbf32b)
                "url_duration": 15811200,

(left is meant to be 3.0.2, right is meant to be 3.0.1).

Batch uses the field from inside the config file to choose latest, it happens that it has used the correct one in the most recent run for it but it depends on the order the dict is parsed in so 3.0.1 could be used accidentally. Only difference is artemis duration.

**Comment by Arun-bioinformatics** [comment]
Latest config file `dias_CEN_config_GRCh37_v3.0.3.json` has been uploaded onto DNANexus as `file-Gfqj2bj4K7XfZVGvB380X3x1` and tested. The version field in DNAnexus alligns with the version from the Github file.
DNAnexus log:
![image](https://github.com/eastgenomics/egg5_dias_CEN_config/assets/75141216/9a5b45bf-7253-4359-a866-eb6f28912c5d)
File in Github:
![image](https://github.com/eastgenomics/egg5_dias_CEN_config/assets/75141216/29769e43-4436-4593-93ca-d2a8ec2facf4)
